### ISSUE TITLE
CPU LIMIT

### ISSUE THREAD

**Issue by taimaiduc** [sickcodes/Docker-OSX#247] opened 2021-04-15 08:57 UTC
# OS related issued, please help us identify the issue by posting the output of this
![image](https://user-images.githubusercontent.com/10907980/114842504-1a674c80-9e03-11eb-815b-1fe8b3c7cce8.png)

Running 
```
docker run -it \
    --cpus=12 \
    --device /dev/kvm \
    -p 50922:10022 \
    -v "${PWD}/macos.img:/image" \
    -v /tmp/.X11-unix:/tmp/.X11-unix \
    -e "DISPLAY=${DISPLAY:-:0.0}" \
    -e RAM=16 \
    -e CORES=8 \
    sickcodes/docker-osx:naked
```

error 
```
+ exec qemu-system-x86_64 -m 16000 -cpu Penryn,vendor=GenuineIntel,+invtsc,vmware-cpuid-freq=on,+pcid,+ssse3,+sse4.2,+popcnt,+avx,+aes,+xsave,+xsaveopt,check -machine q35,accel=kvm:tcg -smp 4,cores=8 -usb -device usb-kbd -device usb-tablet -device 'isa-applesmc,osk=ourhardworkbythesewordsguardedpleasedontsteal(c)AppleComputerInc' -drive if=pflash,format=raw,readonly,file=/home/arch/OSX-KVM/OVMF_CODE.fd -drive if=pflash,format=raw,file=/home/arch/OSX-KVM/OVMF_VARS-1024x768.fd -smbios type=2 -audiodev alsa,id=hda -device ich9-intel-hda -device hda-duplex,audiodev=hda -device ich9-ahci,id=sata -drive id=OpenCoreBoot,if=none,snapshot=on,format=qcow2,file=/home/arch/OSX-KVM/OpenCore-Catalina/OpenCore-nopicker.qcow2 -device ide-hd,bus=sata.2,drive=OpenCoreBoot -drive id=MacHDD,if=none,file=/image,format=qcow2 -device ide-hd,bus=sata.4,drive=MacHDD -netdev user,id=net0,hostfwd=tcp::10022-:22,hostfwd=tcp::5900-:5900, -device vmxnet3,netdev=net0,id=net0,mac=52:54:00:09:49:17 -monitor stdio -vga vmware
qemu-system-x86_64: Invalid CPU topology deprecated: sockets (0) * dies (1) * cores (8) * threads (1) != maxcpus (4)

```

**Comment by sickcodes** [comment] 2021-04-15 10:02
Duplicate of https://github.com/sickcodes/Docker-OSX/issues/248

**Closed by sickcodes** 2021-04-15 10:02 UTC
